---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```
# intro_to_r

The goal of this repository is to introduce some topics to novice R users. Sometimes the most intimidating part of anything with a command line interface is starting. So let's start with a constructive was of getting started.

## Getting R

* First step is to go to CRAN and download the base version of R for your operating system at [https://cran.r-project.org/](https://cran.r-project.org/)

* Next download RStudio for your operating system. This can be done at [https://www.rstudio.com/products/rstudio/download/](https://www.rstudio.com/products/rstudio/download/). You want the open source RStudio Desktop. It's free.

After you have installed them both (in that order) open up R Studio! This will be your IDE or integrated development environment. RStudio has done an amazing job with all the features and has really made R into an enterprise ready solution.

## Getting the Example Documents

The next step is pulling down these documents for use
